version: '3.3'
services:
    iSponsorBlockTV:
        image: ghcr.io/dmunozv04/isponsorblocktv
        container_name: iSponsorBlockTV
        restart: unless-stopped
        volumes:
        - ./sponser:/app/data #made so it makes a folder here the yml is called and ran