version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 890:80
      - 8090:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=true
      - NEXTCLOUD_DATADIR=/rdd/nextcloud-aio
      - NEXTCLOUD_UPLOAD_LIMIT=100G
      - NEXTCLOUD_MEMORY_LIMIT=2000M

 volumes:
   nextcloud_aio_mastercontainer:
     name: nextcloud_aio_mastercontainer








