version: '3'


services:

  nc:

    image: nextcloud:apache #nextcloud standalone image

    environment:

      - NEXTCLOUD_DATADIR=/rdd/nextcloud-data #changed the data dir so that i can use my raid array for it

      - POSTGRES_HOST=db

      - POSTGRES_PASSWORD=nextcloud

      - POSTGRES_DB=nextcloud

      - POSTGRES_USER=nextcloud

      - PHP_MEMORY_LIMIT=1G

      - PHP_UPLOAD_LIMIT=10G

    ports:

      - 880:80

    restart: always

    volumes:

      - /rdd/nextcloud-data:/var/www/html

    depends_on:

      - db

  db:

    image: postgres:alpine #Data base

    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud

    restart: always

    volumes:

      - db_data:/var/lib/postgresql/data

    expose:

      - 5432


networks:
   uh:
    driver: bridge
  

volumes:
  db_data:

  nc_data:
